sudo: required

language: bash

addons:
  apt:
    packages:
      - sshpass

services:
  - docker

before_install:
  - docker build -t stefaneng/comp490-primer .
  - docker run -d -p 80:80 stefaneng/comp490-primer
  - docker ps -a
  - docker run stefaneng/comp490-primer /bin/sh -c "true"

script:
  - curl -i localhost/cgi-bin/index.cgi

after_success:
  - tar -zcf package.tgz public_html
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o stricthostkeychecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e scp -o stricthostkeychecking=no deploy.sh $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh

env:
  global:
    - secure: "G0cKMzzsnvZsDLYzbizKD3Jxmi6ZTQq+UZwSmLhVg4g5EvxgUc4HE1bjtogUlt0373dZlEdd2ozOaP9NClo7feWpcNwUNWi6SMbQ4e3Ib9qgNb7sSOiadEob8xW9LkOglLz/Q8E0H4Ciq60Rd5xc29u7r9R9ccOiPjrTGS0Pc2N5jPCgO5QSpfqT9y0xmo1hbKafT9NzI+xy6YsOyxY/vsmFP6Su+MoD3wY5thCod/sT0YVIyReGQ6oszhXIhtkSjBcBJSAXgt/h5zXR/aCx2S5xd7/TDZZr9oAb8av/UIfLf8pC4DHWRAtZsuVpIaRjdgNKNNjmufIfwQR1MX+PVDPYzMEnTdWnjJfzJEG8SPCqr/tyzTrgQCr7+R9yhX1PuOxGmEw26W6dyQZ35hMd5HhV4pKltjrSHsHCy0ivC+fOBQ4dq96DQSecqh39OBmC/W0bYQrHaLotgtuAdvnZiHUTnb4OAXW4kpcTNVgI+vKMLPGVUYIwun1nLl3e+jcGsgpHBkjC8RQPhGnvoXNWVl9u6fv2fVI5LBLzfp92u9i5ROYsJcZ/Tq/Lru0kXeUl9ty7gjWW++94EVk2goi/zgfIBVVYgSKkTwTeFWATHvv2qJPrCpzF9N97/1AfrAWt6bC4Ll/OjYiLIGfOzdFqUUSaUxTSUJysHELBr51OR80="
    - secure: "IQl6cqDf/I4bQOh63l65/7ROtBfTdT9feapPszRTNZiis8vEFuIyMKvDfxpXVKu8F411NzpfC124F4ovxvgnLEiwz3r1m6v5l9t8n1jFYX39kR/rcv3HI1WAIldnr8+F7uLmvWosqSRGiOzWa8brbHFxxBnUdysgHjXnmzkcnfK5S3nAhwf6PvI4EpjTmXD3SCAV08eDb58E026o6FjzQ3wJz3bOeZp7GqiBDySRwQWw386aF8jvJb+H/o//01WMBC57vTJapso3yVV4LuZPI0B5JwWRZJy5zPfOxijD880N12Ek9DKYhDkd3dV+CqBZBjBEjEYQYsBSUUWNIDeKEvMZZ/P+HsUnkTiblGblCqKDw3Tte3vjc+hLifQwsvW74mRiNW8AC8EsPMhfl82K3UWFar6GEwiu2AbqFNUbWku0OzV3VZvrCGV9vD/JRGbHqHrMUpT8WnEfMHPHk/g2KV74SWOSbvXXWDqqxKx0Tcp7wnIOuZnOFbMum3XrbINkfq3lgWQ9kaf1vjB1q5NI0zV8Drv97G/x2WDZ3WzXAAfCSx4hF+kXlj6mYM6VLyaik+ykCppUKHoWInycE01aJ9XUfQ1/+PWjNXa94LjrDJq23d1PAhbHxpoOzzT0XCt1dCIShapUxdCh2pgJ3jESsw4BxD0jxiTWJCbSrJ7zBl4="
    - secure: "OnGpntqCAujwBaqEtYZzUSm+5Z2v4XClsGQcuE8GzdRmG2z5bYQ2lshMn+I9hqt4ST9DHqhTgw9xaDDs8NiuhLOzeJ3kBCo4k1iROf+AWzFBGaLR7jXHjwqCJYXJl3Ch7HajXypROIY+9i0UnLFZPQmNQA+M/UZ4MXI+Abo2xbo5GHpz84gu1EnoF2SqEVyT9VbFImpxvKGlr9pIa/80dGY7bnw/Qt9PetJEptq06Er99I2EzboayMk9aNeMpi5mRKl5li/pEBDC/jB2z5nrNxJy8oakpqVV7ED5jIpCSPQuBj/QG3BfIxQomQ6Wrha9v7+BdROLTLZ1W/Hht6YX0X0058u9QquiRsgaepaL29kN5g4Har4lBFy4X+Keekn+WQOnwrMYY/4t8gOh51XN1MSUQhq5rN0TX+6m8IvxUDi2X2d8X5MbPtYzLdbp8X7n9hvcUvwlbMNO+tD+5v2tmIrZM48Utn6eEGb4j4scp355l/cK7Z06pP0wytua0jVFNNPL1fT4KzMXK9ETeJbu0dE8odWKC+d8DGJ5FNHoeBNBUeNEkUveSkQMzVH1EViC2HVW3gZ05H8p1qLzf7+ERG6qWYF/PTlYLznH6TaytZ7FsSjU4M9lAEADERxXsgvN07Qq6PhckUVOKq1SlM7uBiwWri0DKd75a03p+nShfXQ="
    - secure: "NBZHpAE5dOsv/oiPKnzAdr7JyrrLleWYHB45VmuDUq6LEXKzSB+Nyl8ttGxh890Y9RTdvkR6nW9XqHL9dnlGIaGrHwfG4znOABuPP9oYuzdMRIHKwtuIb/mfhNZR0e5pj0mp0Cp41tMhSddXZpjlnFgwHrqy7imZtsZgZWO/pf5IsPkNinU4MRysHDGDH558xyAxWfYd5DRxGOG7Yfxj9iuMSCYakBjauYWk7nM0uA+9LEFs0sOCNApm1oEnmbjPDStOTPkKKbhRE2nGQqUutAQSpnQnN0FCUuhvbovyb2gq5NGJe4m6b5npyPdXlZrGnEd8/ROm8agmZczFVq0E58T9VQrDGSxTbcMMBybeDImag3fUfl5tyLh91JOiiNDcr+pZfiuuGWWQiNzBYgoxEMOUY8O420wkPTVjpk42u+KUMURCn1YOrUxzga07B+Jxj5A208Zz211TVZVl5cW5P0ecQLNCURsh9vOlkDGVrAo/HfZsiOkVAB3idgqDdA+cXgY3Z5ZljukCBYeU0WeNDxueiEl/gaa7W71BW4faPScyPCeabY/rsFHPdCIeavtgNnXy2gb8HgfbqaWMafiFyI8VC6LgWRMmdj4NPnCPzyabKng7Vk0hmkoHKA82R7GKakuKq6R7dY+biU6ecoMI7gO5uI2rKChU9pv6a8S2Mh0="